/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Tue Sep 07 21:57:56 ADT 2021 ----! */

#include <jni.h>
#include <stdlib.h>

#include <assert.h>


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: SQLiteResponse sqlc_api_db_open(int sqlc_api_version, java.lang.String filename, int flags)
 *     C function: sqlc_handle_ct *  sqlc_api_db_open(int sqlc_api_version, const char *  filename, int flags);
 */
JNIEXPORT jobject JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1api_1db_1open1__ILjava_lang_String_2I(JNIEnv *env, jclass _unused, jint sqlc_api_version, jstring filename, jint flags) {
  const char* _strchars_filename = NULL;
  sqlc_handle_ct *  _res;
  if ( NULL != filename ) {
    _strchars_filename = (*env)->GetStringUTFChars(env, filename, (jboolean*)NULL);
  if ( NULL == _strchars_filename ) {
      (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/OutOfMemoryError"),
                       "Failed to get UTF-8 chars for argument \"filename\" in native dispatcher for \"sqlc_api_db_open\"");
      return 0;
    }
  }
  _res = sqlc_api_db_open((int) sqlc_api_version, (char *) _strchars_filename, (int) flags);
  if ( NULL != filename ) {
    (*env)->ReleaseStringUTFChars(env, filename, _strchars_filename);
  }
  if (NULL == _res) return NULL;
  return (*env)->NewDirectByteBuffer(env, _res, sizeof(sqlc_handle_ct));
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_api_version_check(int sqlc_api_version)
 *     C function: int sqlc_api_version_check(int sqlc_api_version);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1api_1version_1check__I(JNIEnv *env, jclass _unused, jint sqlc_api_version) {
  int _res;
  _res = sqlc_api_version_check((int) sqlc_api_version);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_db_close(long db)
 *     C function: int sqlc_db_close(sqlc_handle_t db);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1db_1close__J(JNIEnv *env, jclass _unused, jlong db) {
  int _res;
  _res = sqlc_db_close((sqlc_handle_t) db);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_db_errcode(long db)
 *     C function: int sqlc_db_errcode(sqlc_handle_t db);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1db_1errcode__J(JNIEnv *env, jclass _unused, jlong db) {
  int _res;
  _res = sqlc_db_errcode((sqlc_handle_t) db);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: java.lang.String sqlc_db_errmsg_native(long db)
 *     C function: const char *  sqlc_db_errmsg_native(sqlc_handle_t db);
 */
JNIEXPORT jstring JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1db_1errmsg_1native__J(JNIEnv *env, jclass _unused, jlong db) {
  const char *  _res;
  _res = sqlc_db_errmsg_native((sqlc_handle_t) db);
  if (NULL == _res) return NULL;
  return (*env)->NewStringUTF(env, _res);
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_db_key_native_string(long db, java.lang.String key_string)
 *     C function: int sqlc_db_key_native_string(sqlc_handle_t db, char *  key_string);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1db_1key_1native_1string__JLjava_lang_String_2(JNIEnv *env, jclass _unused, jlong db, jstring key_string) {
  const char* _strchars_key_string = NULL;
  int _res;
  if ( NULL != key_string ) {
    _strchars_key_string = (*env)->GetStringUTFChars(env, key_string, (jboolean*)NULL);
  if ( NULL == _strchars_key_string ) {
      (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/OutOfMemoryError"),
                       "Failed to get UTF-8 chars for argument \"key_string\" in native dispatcher for \"sqlc_db_key_native_string\"");
      return 0;
    }
  }
  _res = sqlc_db_key_native_string((sqlc_handle_t) db, (char *) _strchars_key_string);
  if ( NULL != key_string ) {
    (*env)->ReleaseStringUTFChars(env, key_string, _strchars_key_string);
  }
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: long sqlc_db_last_insert_rowid(long db)
 *     C function: sqlc_long_t sqlc_db_last_insert_rowid(sqlc_handle_t db);
 */
JNIEXPORT jlong JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1db_1last_1insert_1rowid__J(JNIEnv *env, jclass _unused, jlong db) {
  sqlc_long_t _res;
  _res = sqlc_db_last_insert_rowid((sqlc_handle_t) db);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: SQLiteResponse sqlc_db_open(java.lang.String filename, int flags)
 *     C function: sqlc_handle_ct *  sqlc_db_open(const char *  filename, int flags);
 */
JNIEXPORT jobject JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1db_1open1__Ljava_lang_String_2I(JNIEnv *env, jclass _unused, jstring filename, jint flags) {
  const char* _strchars_filename = NULL;
  sqlc_handle_ct *  _res;
  if ( NULL != filename ) {
    _strchars_filename = (*env)->GetStringUTFChars(env, filename, (jboolean*)NULL);
  if ( NULL == _strchars_filename ) {
      (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/OutOfMemoryError"),
                       "Failed to get UTF-8 chars for argument \"filename\" in native dispatcher for \"sqlc_db_open\"");
      return 0;
    }
  }
  _res = sqlc_db_open((char *) _strchars_filename, (int) flags);
  if ( NULL != filename ) {
    (*env)->ReleaseStringUTFChars(env, filename, _strchars_filename);
  }
  if (NULL == _res) return NULL;
  return (*env)->NewDirectByteBuffer(env, _res, sizeof(sqlc_handle_ct));
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: SQLiteResponse sqlc_db_prepare_st(long db, java.lang.String sql)
 *     C function: sqlc_handle_ct *  sqlc_db_prepare_st(sqlc_handle_t db, const char *  sql);
 */
JNIEXPORT jobject JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1db_1prepare_1st1__JLjava_lang_String_2(JNIEnv *env, jclass _unused, jlong db, jstring sql) {
  const char* _strchars_sql = NULL;
  sqlc_handle_ct *  _res;
  if ( NULL != sql ) {
    _strchars_sql = (*env)->GetStringUTFChars(env, sql, (jboolean*)NULL);
  if ( NULL == _strchars_sql ) {
      (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/OutOfMemoryError"),
                       "Failed to get UTF-8 chars for argument \"sql\" in native dispatcher for \"sqlc_db_prepare_st\"");
      return 0;
    }
  }
  _res = sqlc_db_prepare_st((sqlc_handle_t) db, (char *) _strchars_sql);
  if ( NULL != sql ) {
    (*env)->ReleaseStringUTFChars(env, sql, _strchars_sql);
  }
  if (NULL == _res) return NULL;
  return (*env)->NewDirectByteBuffer(env, _res, sizeof(sqlc_handle_ct));
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_db_total_changes(long db)
 *     C function: int sqlc_db_total_changes(sqlc_handle_t db);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1db_1total_1changes__J(JNIEnv *env, jclass _unused, jlong db) {
  int _res;
  _res = sqlc_db_total_changes((sqlc_handle_t) db);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: java.lang.String sqlc_errstr_native(int errcode)
 *     C function: const char *  sqlc_errstr_native(int errcode);
 */
JNIEXPORT jstring JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1errstr_1native__I(JNIEnv *env, jclass _unused, jint errcode) {
  const char *  _res;
  _res = sqlc_errstr_native((int) errcode);
  if (NULL == _res) return NULL;
  return (*env)->NewStringUTF(env, _res);
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: void sqlc_handle_ct_delete(SQLiteResponse handle_ct)
 *     C function: void sqlc_handle_ct_delete(sqlc_handle_ct *  handle_ct);
 */
JNIEXPORT void JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1handle_1ct_1delete1__Ljava_nio_ByteBuffer_2(JNIEnv *env, jclass _unused, jobject handle_ct) {
  sqlc_handle_ct * _handle_ct_ptr = NULL;
    if ( NULL != handle_ct ) {
        _handle_ct_ptr = (sqlc_handle_ct *) (((char*) (*env)->GetDirectBufferAddress(env, handle_ct)) + 0);
    }
  sqlc_handle_ct_delete((sqlc_handle_ct *) _handle_ct_ptr);
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_st_bind_double(long st, int pos, double val)
 *     C function: int sqlc_st_bind_double(sqlc_handle_t st, int pos, double val);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1bind_1double__JID(JNIEnv *env, jclass _unused, jlong st, jint pos, jdouble val) {
  int _res;
  _res = sqlc_st_bind_double((sqlc_handle_t) st, (int) pos, (double) val);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_st_bind_int(long st, int pos, int val)
 *     C function: int sqlc_st_bind_int(sqlc_handle_t st, int pos, int val);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1bind_1int__JII(JNIEnv *env, jclass _unused, jlong st, jint pos, jint val) {
  int _res;
  _res = sqlc_st_bind_int((sqlc_handle_t) st, (int) pos, (int) val);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_st_bind_long(long st, int pos, long val)
 *     C function: int sqlc_st_bind_long(sqlc_handle_t st, int pos, sqlc_long_t val);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1bind_1long__JIJ(JNIEnv *env, jclass _unused, jlong st, jint pos, jlong val) {
  int _res;
  _res = sqlc_st_bind_long((sqlc_handle_t) st, (int) pos, (sqlc_long_t) val);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_st_bind_null(long st, int pos)
 *     C function: int sqlc_st_bind_null(sqlc_handle_t st, int pos);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1bind_1null__JI(JNIEnv *env, jclass _unused, jlong st, jint pos) {
  int _res;
  _res = sqlc_st_bind_null((sqlc_handle_t) st, (int) pos);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_st_bind_text_native(long st, int col, java.lang.String val)
 *     C function: int sqlc_st_bind_text_native(sqlc_handle_t st, int col, const char *  val);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1bind_1text_1native__JILjava_lang_String_2(JNIEnv *env, jclass _unused, jlong st, jint col, jstring val) {
  const char* _strchars_val = NULL;
  int _res;
  if ( NULL != val ) {
    _strchars_val = (*env)->GetStringUTFChars(env, val, (jboolean*)NULL);
  if ( NULL == _strchars_val ) {
      (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/OutOfMemoryError"),
                       "Failed to get UTF-8 chars for argument \"val\" in native dispatcher for \"sqlc_st_bind_text_native\"");
      return 0;
    }
  }
  _res = sqlc_st_bind_text_native((sqlc_handle_t) st, (int) col, (char *) _strchars_val);
  if ( NULL != val ) {
    (*env)->ReleaseStringUTFChars(env, val, _strchars_val);
  }
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_st_column_count(long st)
 *     C function: int sqlc_st_column_count(sqlc_handle_t st);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1column_1count__J(JNIEnv *env, jclass _unused, jlong st) {
  int _res;
  _res = sqlc_st_column_count((sqlc_handle_t) st);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: double sqlc_st_column_double(long st, int col)
 *     C function: double sqlc_st_column_double(sqlc_handle_t st, int col);
 */
JNIEXPORT jdouble JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1column_1double__JI(JNIEnv *env, jclass _unused, jlong st, jint col) {
  double _res;
  _res = sqlc_st_column_double((sqlc_handle_t) st, (int) col);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_st_column_int(long st, int col)
 *     C function: int sqlc_st_column_int(sqlc_handle_t st, int col);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1column_1int__JI(JNIEnv *env, jclass _unused, jlong st, jint col) {
  int _res;
  _res = sqlc_st_column_int((sqlc_handle_t) st, (int) col);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: long sqlc_st_column_long(long st, int col)
 *     C function: sqlc_long_t sqlc_st_column_long(sqlc_handle_t st, int col);
 */
JNIEXPORT jlong JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1column_1long__JI(JNIEnv *env, jclass _unused, jlong st, jint col) {
  sqlc_long_t _res;
  _res = sqlc_st_column_long((sqlc_handle_t) st, (int) col);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: java.lang.String sqlc_st_column_name(long st, int col)
 *     C function: const char *  sqlc_st_column_name(sqlc_handle_t st, int col);
 */
JNIEXPORT jstring JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1column_1name__JI(JNIEnv *env, jclass _unused, jlong st, jint col) {
  const char *  _res;
  _res = sqlc_st_column_name((sqlc_handle_t) st, (int) col);
  if (NULL == _res) return NULL;
  return (*env)->NewStringUTF(env, _res);
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: java.lang.String sqlc_st_column_text_native(long st, int col)
 *     C function: const char *  sqlc_st_column_text_native(sqlc_handle_t st, int col);
 */
JNIEXPORT jstring JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1column_1text_1native__JI(JNIEnv *env, jclass _unused, jlong st, jint col) {
  const char *  _res;
  _res = sqlc_st_column_text_native((sqlc_handle_t) st, (int) col);
  if (NULL == _res) return NULL;
  return (*env)->NewStringUTF(env, _res);
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_st_column_type(long st, int col)
 *     C function: int sqlc_st_column_type(sqlc_handle_t st, int col);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1column_1type__JI(JNIEnv *env, jclass _unused, jlong st, jint col) {
  int _res;
  _res = sqlc_st_column_type((sqlc_handle_t) st, (int) col);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_st_finish(long st)
 *     C function: int sqlc_st_finish(sqlc_handle_t st);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1finish__J(JNIEnv *env, jclass _unused, jlong st) {
  int _res;
  _res = sqlc_st_finish((sqlc_handle_t) st);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_st_step(long st)
 *     C function: int sqlc_st_step(sqlc_handle_t st);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1st_1step__J(JNIEnv *env, jclass _unused, jlong st) {
  int _res;
  _res = sqlc_st_step((sqlc_handle_t) st);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: SQLiteResponse sqlc_stp_context_create(long db)
 *     C function: sqlc_handle_ct *  sqlc_stp_context_create(sqlc_handle_t db);
 */
JNIEXPORT jobject JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1stp_1context_1create1__J(JNIEnv *env, jclass _unused, jlong db) {
  sqlc_handle_ct *  _res;
  _res = sqlc_stp_context_create((sqlc_handle_t) db);
  if (NULL == _res) return NULL;
  return (*env)->NewDirectByteBuffer(env, _res, sizeof(sqlc_handle_ct));
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: void sqlc_stp_context_delete(long stp_context_h)
 *     C function: void sqlc_stp_context_delete(sqlc_handle_t stp_context_h);
 */
JNIEXPORT void JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1stp_1context_1delete__J(JNIEnv *env, jclass _unused, jlong stp_context_h) {
  sqlc_stp_context_delete((sqlc_handle_t) stp_context_h);
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: SQLiteResponse sqlc_syn_context_create(long db)
 *     C function: sqlc_handle_ct *  sqlc_syn_context_create(sqlc_handle_t db);
 */
JNIEXPORT jobject JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1syn_1context_1create1__J(JNIEnv *env, jclass _unused, jlong db) {
  sqlc_handle_ct *  _res;
  _res = sqlc_syn_context_create((sqlc_handle_t) db);
  if (NULL == _res) return NULL;
  return (*env)->NewDirectByteBuffer(env, _res, sizeof(sqlc_handle_ct));
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: void sqlc_syn_context_delete(long syn_context_h)
 *     C function: void sqlc_syn_context_delete(sqlc_handle_t syn_context_h);
 */
JNIEXPORT void JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1syn_1context_1delete__J(JNIEnv *env, jclass _unused, jlong syn_context_h) {
  sqlc_syn_context_delete((sqlc_handle_t) syn_context_h);
}


/*   Java->C glue code:
 *   Java package: io.liteglue.SQLiteNative
 *    Java method: int sqlc_tokenizer_register_all(long db, long syn_context_h, long stp_context_h)
 *     C function: int sqlc_tokenizer_register_all(sqlc_handle_t db, sqlc_handle_t syn_context_h, sqlc_handle_t stp_context_h);
 */
JNIEXPORT jint JNICALL 
Java_io_liteglue_SQLiteNative_sqlc_1tokenizer_1register_1all__JJJ(JNIEnv *env, jclass _unused, jlong db, jlong syn_context_h, jlong stp_context_h) {
  int _res;
  _res = sqlc_tokenizer_register_all((sqlc_handle_t) db, (sqlc_handle_t) syn_context_h, (sqlc_handle_t) stp_context_h);
  return _res;
}


